name: Deploy to Firebase Cloud Functions on merge
on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'

env:
  PROJECT_ID: 'aaap-app-in-a-box'

jobs:
  build-and-deploy-cloud-functions:
    name: Firebase build Cloud Functions and deploy
    runs-on: ubuntu-latest
    env:
      working-directory: "backend"
      functions-directory: "backend/functions"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.functions-directory }}/.nvmrc

      - name: Install dependencies
        working-directory: ${{ env.functions-directory }}
        run: npm ci

      - name: Deploy cloud functions to Firebase
        uses: w9jds/firebase-action@v13.16.0
        with:
          args: deploy --only functions,firestore:rules,storage
        env:
          PROJECT_PATH: './backend'
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAAP_APP_IN_A_BOX }}
